from pathlib import Path
import glob
import pandas as pd
import numpy as np

######## RUN THIS TO CREATE DAG ########
# snakemake --cores 4 --dag 2>/dev/null | grep -v "Including" | dot -Tpdf > dag.pdf
########################################


configfile: "config.yaml"

ar6_variables = config["ar6_variables"]
tread_variables = config["tread_variables"]
gwls = config["gwls"]
ssp_scenarios = config["ssp_scenarios"]
branches = config["branches"]


PROJECT_MAIN_DIR = Path(workflow.basedir).resolve()  # Snakefile directory
ROOT_DIR = PROJECT_MAIN_DIR.parents[1]              # go up 3 levels to chuang_lab_tmu
WORK_DIR = ROOT_DIR / "work"
PROJECT_WORK_DIR = WORK_DIR / "ssp_rcp"

DATA_DIR = PROJECT_WORK_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
INTERIM_DIR = DATA_DIR / "interim"
PROCESSED_DIR = DATA_DIR / "processed"

GWL_RAW_DIR   = RAW_DIR / "GWL"
AR6_RAW_DIR   = RAW_DIR / "AR6"
TREAD_RAW_DIR = RAW_DIR / "TREAD"
NETCDF_DIR    = INTERIM_DIR / "NetCDF"
GWL_NETCDF_DIR = NETCDF_DIR / "GWL_NetCDF"
AR6_NETCDF_DIR = NETCDF_DIR / "AR6_NetCDF"
TREAD_NETCDF_DIR = NETCDF_DIR / "TREAD_NetCDF"

FIGURES_DIR = PROJECT_WORK_DIR / "figures"

# List of all directories you want to create
dirs_to_create = [
    WORK_DIR,
    PROJECT_WORK_DIR,
    DATA_DIR,
    RAW_DIR,
    INTERIM_DIR,
    PROCESSED_DIR,
    GWL_RAW_DIR,
    AR6_RAW_DIR,
    TREAD_RAW_DIR,
    NETCDF_DIR,
    GWL_NETCDF_DIR,
    AR6_NETCDF_DIR,
    TREAD_NETCDF_DIR,
    FIGURES_DIR
]

dirs_to_create = [
    WORK_DIR,
    PROJECT_WORK_DIR,
    DATA_DIR,
    RAW_DIR,
    INTERIM_DIR,
    PROCESSED_DIR,
    GWL_RAW_DIR,
    AR6_RAW_DIR,
    TREAD_RAW_DIR,
    NETCDF_DIR,
    GWL_NETCDF_DIR,
    AR6_NETCDF_DIR,
    TREAD_NETCDF_DIR,
    FIGURES_DIR
]

rule make_dirs:
    # Output can just be the top-level dir
    output:
        PROJECT_WORK_DIR = directory(PROJECT_WORK_DIR)
    run:
        for directory in dirs_to_create:
            abs_path = Path(directory).resolve()
            if not abs_path.exists():
                print(f"Creating directory: {abs_path}")
                abs_path.mkdir(parents=True, exist_ok=True)
            else:
                print(f"Directory already exists: {abs_path}")

for branch in branches:
    print(f"Including rules for branch: {branch}")
    include: f"rules/{branch}.smk"

all_inputs = [
    NETCDF_DIR / "ar6_all.nc",
    NETCDF_DIR / "gwl_all.nc",
    # NETCDF_DIR / "tread_all.nc"
]


# Keep only files that actually exist or will be created
all_inputs = [str(f) for f in all_inputs]



rule all:
    input:
        all_inputs





